### ISSUE TITLE
Fix Transition for Navbar Elements

### ISSUE THREAD

**Issue by StephenODea54** [Hack-Weekly/onyx-sal-blog#56]
When you hover over the individual navbar elements, the text size increases but the text color does not change if you hover over the element but not the text itself.

**Comment by lakharashubham007** [comment]
I can fix this issue .

**Comment by StephenODea54** [comment]
@nathanjslim @lakharashubham007 I just accidentally fixed this while trying to center text within an li element for longer than I'd like to admit lol.
